site_name: FAIR2ADAPT Knowledge Services
theme:
  name: material
  logo: images/f2a_logo.png
  favicon: images/f2a_logo.png
  palette:
    scheme: default
    primary: custom
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - Services:
      - FDO Services Interfaces for Data Handling in CCA: services/T_4_1_data_handeling.md
      - FDO Services for Knowledge Synthesis in CCA: services/T_4_2_knowledge_synthesis.md
      - Multilingual Generative Question Answering in CCA: services/T_4_3_multilingual_generative_qa.md
      - Publishing Knowledge with Customizable Dashboards: services/T_4_4_template_guide_dashboard.md
  - Case Studies:
      - Case Study 1: case_studies/cs1.md
      - Case Study 2: case_studies/cs2.md
      - Case Study 3: case_studies/cs3.md
      - Case Study 4: case_studies/cs4.md
      - Case Study 5: case_studies/cs5.md
      - Case Study 6: case_studies/cs6.md

# Optional: enable an "Edit this page" button that links to GitHub
extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/FAIR2Adapt/knowledge-services
repo_name: GitHub
edit_uri: edit/main/docs/

# Optional: plugins for search and more
plugins:
  - search
  